### ISSUE TITLE
TVHeadend_7.0.0.0 missing in plugin repo

### ISSUE THREAD

**Issue by ggogel** [jellyfin/jellyfin-plugin-tvheadend#30] opened 2021-01-05 12:31 UTC
The latest version TVHeadend_7.0.0.0 for Jellyfin 10.7 is missing in the plugin repo. The version 6.0.0.0 didn't even start for me on a fresh 10.7RC2. I've now built it myself and it works. Please add it to the repo.

**Comment by joshuaboniface** [comment] 2021-01-05 16:21
Confirmed - it looks like the v7 build failed on Dec 6th and was never populated to the plugin repo.

This has been fixed, and v7 should now be present.

**Comment by mcoms** [comment] 2021-01-25 20:34
hmm, still doesn't seem to be present... 🤔
```
2021-01-25 20:30:45 | [20:30:45] [ERR] [20] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://192.168.0.10:8096/Packages/Installed/TVHeadend?AssemblyGuid=3fd018e5-5e78-4e58-b280-a0c068febee0&version=7.0.0.0
2021-01-25 20:30:45 | MediaBrowser.Common.Extensions.ResourceNotFoundException: Package not found: TVHeadend
2021-01-25 20:30:45 | at MediaBrowser.Api.PackageService.Post(InstallPackage request)
```

**Comment by crobibero** [comment] 2021-01-25 20:44
it sure isn't
https://repo.jellyfin.org/releases/plugin/jellyfin-plugin-tvheadend/
cc @joshuaboniface

**Comment by ggogel** [comment] 2021-01-25 20:52
It was available though 🤔

**Comment by mcoms** [comment] 2021-01-25 22:57
Ah, no my bad — Jellyfin was running at `10.6.4`. It still lists `7.0.0.0` available for installation in the UI despite `targetAbi` being `10.7.0.0`.

I have: "Jellyfin Stable: https://repo.jellyfin.org/releases/plugin/manifest-stable.json" as the only repository, which lists:
```
[
...
    {
        "guid": "3fd018e5-5e78-4e58-b280-a0c068febee0",
        "name": "TVHeadend",
        "description": "Manage TVHeadend from Jellyfin",
        "overview": "Manage TVHeadend from Jellyfin",
        "owner": "jellyfin",
        "category": "LiveTV",
        "versions": [
            {
                "version": "7.0.0.0",
                "changelog": "changelog\n",
                "targetAbi": "10.7.0.0",
                "sourceUrl": "https://repo.jellyfin.org/releases/plugin/tvheadend/tvheadend_7.0.0.0.zip",
                "checksum": "1abbfce737b6962f4b1b2255dc63e932",
                "timestamp": "2021-01-05T16:20:33Z"
            },
            {
                "version": "6.0.0.0",
                "changelog": "changelog\n",
                "targetAbi": "10.6.0.0",
                "sourceUrl": "https://repo.jellyfin.org/releases/plugin/tvheadend/tvheadend_6.0.0.0.zip",
                "checksum": "143c34fd70d7173b8912cc03ce4b517d",
                "timestamp": "2020-07-20T01:33:15Z"
            }
        ]
    }
...
]
```
and those `sourceUrl`s do exist (at least they're on the `fra1` mirror I was hitting), so panic over I think!

For others getting a "Package not found" error: Double check the version of Jellyfin that's running, and whether it's compatible with the TVHeadend plugin version you're trying to install.

**Comment by crobibero** [comment] 2021-01-25 23:01
They're also on the `sfo1` mirror, so maybe just not on `repo`
Marking as closed as the zip actually exists

**Closed by crobibero** 2021-01-25 23:01 UTC
